# -*- coding: utf-8 -*-
"""EDA&Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h1SIpIdAJTawyK50hbXfgSgZ3NlcXxm5

**0. Moutning GDrive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**1. Importing Required Libraries**"""

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F

from pyspark.sql.types import NumericType, StringType, BooleanType
from pyspark.sql.window import Window
from pyspark.sql.types import (
    IntegerType, LongType, FloatType,
    DoubleType, DecimalType, ShortType
)

from pyspark.ml.feature import VectorAssembler
from pyspark.ml.stat import Correlation

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import textwrap

"""**2. Load + quick audit**"""

def get_spark(app_name: str = "DDAM_LendingClub") -> SparkSession:
    return (
        SparkSession.builder
        .appName(app_name)
        .getOrCreate()
    )


def load_lendingclub_csv(
    spark: SparkSession,
    path: str,
    header: bool = True,
    infer_schema: bool = True,
    multiline: bool = True,
    escape: str = "\"",
) -> DataFrame:
    return (
        spark.read
        .option("header", header)
        .option("inferSchema", infer_schema)
        .option("multiLine", multiline)
        .option("escape", escape)
        .csv(path)
    )


def dataset_summary(df: DataFrame) -> dict:
    return {
        "rows": df.count(),
        "columns": len(df.columns),
    }


def main() -> DataFrame:
    path = "/content/drive/MyDrive/DDAM/accepted_2007_to_2018Q4.csv"

    spark = get_spark()
    df_raw = load_lendingclub_csv(spark, path)

    summary = dataset_summary(df_raw)
    print("Loaded df_raw.")
    print("Rows:", summary["rows"])
    print("Columns:", summary["columns"])

    return df_raw

df_raw = main()

def inspect_dataframe(df: DataFrame, n: int = 5) -> None:
    df.printSchema()
    df.show(n)
    print("Column Names:")
    print(df.columns)


# call
inspect_dataframe(df_raw)

def get_column_types(df: DataFrame) -> None:
    numeric_types = (
        IntegerType, LongType, FloatType,
        DoubleType, DecimalType, ShortType
    )

    numerical_cols = [
        field.name
        for field in df.schema.fields
        if isinstance(field.dataType, numeric_types)
    ]

    categorical_cols = [
        field.name
        for field in df.schema.fields
        if not isinstance(field.dataType, numeric_types)
    ]

    print("Number of numerical columns:", len(numerical_cols))
    print("Number of categorical columns:", len(categorical_cols))

    print("\nNumerical Columns:")
    print(numerical_cols)

    print("\nCategorical Columns:")
    print(categorical_cols)

get_column_types(df_raw)

"""**3. Define target + keep only final outcomes**"""

def null_check(df: DataFrame, columns: list[str]) -> None:
    total_rows = df.count()
    print("Total rows:", total_rows)

    for c in columns:
        null_count = df.filter(F.col(c).isNull()).count()
        pct = (null_count / total_rows) * 100 if total_rows else 0.0
        print(f"{c} nulls: {null_count} ({pct:.4f}%)")


# call
null_check(df_raw, ["loan_status", "int_rate"])

def show_group_count(
    df: DataFrame,
    column: str,
    descending: bool = True,
    truncate: bool = False,
) -> None:
    result = df.groupBy(column).count()
    result = result.orderBy(F.desc("count")) if descending else result.orderBy("count")
    result.show(truncate=truncate)


# call
show_group_count(df_raw, "loan_status")

def plot_category_distribution(
    df,
    column,
    top_n=None,
    figsize=(8, 4.5),
    wrap_width=26,
    sort_desc=True
):
    agg = df.groupBy(column).count()
    agg = agg.orderBy(F.desc("count")) if sort_desc else agg.orderBy("count")

    pdf = agg.toPandas()

    if top_n is not None and len(pdf) > top_n:
        top = pdf.iloc[:top_n].copy()
        other_count = pdf.iloc[top_n:]["count"].sum()
        other = pd.DataFrame({column: ["Other"], "count": [other_count]})
        pdf = pd.concat([top, other], ignore_index=True)

    pdf[column] = pdf[column].astype(str).apply(
        lambda s: "\n".join(textwrap.wrap(s, width=wrap_width))
    )

    plt.figure(figsize=figsize)
    plt.barh(pdf[column][::-1], pdf["count"][::-1])

    plt.title(f"Distribution of {column}")
    plt.xlabel("Count")
    plt.ylabel(column)

    for i, cnt in enumerate(pdf["count"][::-1].values):
        plt.text(cnt, i, f"  {cnt:,}", va="center", fontsize=9)

    plt.tight_layout()
    plt.show()

plot_category_distribution(df_raw, "loan_status", top_n=None, figsize=(8,4.5), wrap_width=34)

def plot_default_rate_by_grade_from_multiclass(
    df: DataFrame,
    status_col: str = "loan_status",
    grade_col: str = "grade"
) -> None:

    df_bin = (
        df.withColumn(
            "loan_status_label",
            F.when(F.col(status_col).isin("Charged Off", "Default"), F.lit(1))
             .when(F.col(status_col) == "Fully Paid", F.lit(0))
             .otherwise(F.lit(None))
        )
        .filter(F.col("loan_status_label").isNotNull())
    )

    rows = (
        df_bin.groupBy(grade_col)
              .agg(F.avg("loan_status_label").alias("default_rate"))
              .orderBy(grade_col)
              .collect()
    )

    grades = [r[grade_col] for r in rows]
    rates = [r["default_rate"] for r in rows]

    plt.figure(figsize=(4, 3))
    plt.bar(grades, rates)
    plt.title("Default Rate by Grade")
    plt.xlabel("Grade")
    plt.ylabel("Default Rate")
    plt.ylim(0, 1)
    plt.tight_layout()
    plt.show()

# call
plot_default_rate_by_grade_from_multiclass(df_raw)

def prepare_classification_df(
    df: DataFrame,
    status_map: dict,
    target_col: str = "loan_status",
    required_cols: list[str] = None,
) -> DataFrame:

    if required_cols is None:
        required_cols = [target_col, "int_rate"]

    final_statuses = list(status_map.keys())
    map_expr = F.create_map([F.lit(x) for kv in status_map.items() for x in kv])

    df_cls = (
        df.na.drop(subset=required_cols)
          .filter(F.col(target_col).isin(final_statuses))
          .withColumn("label", map_expr[F.col(target_col)])
          .drop(target_col)
    )

    print("Rows after outcome filtering:", df_cls.count())
    df_cls.groupBy("label").count().show()

    default_rate = df_cls.select(
        (F.mean("label") * 100).alias("default_rate_pct")
    ).first()["default_rate_pct"]

    print("Default rate (%):", default_rate)

    return df_cls


# call
final_status_map = {
    "Fully Paid": 0,
    "Charged Off": 1,
    "Default": 1,
    "Does not meet the credit policy. Status:Fully Paid": 0,
    "Does not meet the credit policy. Status:Charged Off": 1,
}

df_cls = prepare_classification_df(df_raw, final_status_map)

def plot_label_distribution(df: DataFrame) -> None:
    rows = (
        df.groupBy("label")
          .count()
          .orderBy("label")
          .collect()
    )

    labels = [r["label"] for r in rows]
    counts = [r["count"] for r in rows]

    total = sum(counts)
    percents = [(c / total) * 100 for c in counts] if total else [0] * len(counts)

    plt.figure(figsize=(4, 3))
    plt.bar([str(l) for l in labels], counts)
    plt.title("Label distribution (counts)")
    plt.xlabel("Label (0=non-default, 1=default)")
    plt.ylabel("Number of loans")
    plt.tight_layout()
    plt.show()

    plt.figure(figsize=(4, 3))
    plt.bar([str(l) for l in labels], percents)
    plt.title("Label distribution (percent)")
    plt.xlabel("Label (0=non-default, 1=default)")
    plt.ylabel("Percent of loans (%)")
    plt.tight_layout()
    plt.show()


# call
plot_label_distribution(df_cls)

def plot_numeric_distribution(
    df,
    column,
    sample_fraction=0.1,
    bins=40,
    figsize=(4,3),
    dropna=True
):

    sdf = df.select(column)

    if dropna:
        sdf = sdf.dropna()

    pdf = sdf.sample(fraction=sample_fraction).toPandas()

    plt.figure(figsize=figsize)
    sns.histplot(pdf[column], bins=bins)

    plt.title(f"Distribution of {column}")
    plt.xlabel(column)
    plt.ylabel("Frequency")

    plt.tight_layout()
    plt.show()

#call
plot_numeric_distribution(df_cls, "int_rate")

import matplotlib.pyplot as plt
import seaborn as sns

def plot_box_by_category(
    df,
    category_col,
    numeric_col,
    sample_fraction=0.1,
    order=None,
    figsize=(4,3),
    dropna=True
):

    sdf = df.select(category_col, numeric_col)

    if dropna:
        sdf = sdf.dropna()

    pdf = sdf.sample(fraction=sample_fraction).toPandas()

    plt.figure(figsize=figsize)
    sns.boxplot(x=category_col, y=numeric_col, data=pdf, order=order)

    plt.title(f"{numeric_col} Distribution by {category_col}")
    plt.xlabel(category_col)
    plt.ylabel(numeric_col)

    plt.tight_layout()
    plt.show()

# call
plot_box_by_category(
    df_cls,
    category_col="grade",
    numeric_col="int_rate",
    order=["A","B","C","D","E","F","G"]
)

import matplotlib.pyplot as plt
import seaborn as sns

def plot_feature_distributions(
    df,
    features,
    sample_fraction=0.05,
    bins=40,
    figsize=(7,5),
    dropna=True
):

    sdf = df.select(features)

    if dropna:
        sdf = sdf.dropna()

    pdf = sdf.sample(fraction=sample_fraction).toPandas()

    plt.figure(figsize=figsize)

    for i, col in enumerate(features, 1):
        plt.subplot(2, 2, i)
        sns.histplot(pdf[col], bins=bins)
        plt.title(f"Distribution of {col}")
        plt.xlabel("")
        plt.ylabel("")

    plt.tight_layout()
    plt.show()

features = ["loan_amnt", "annual_inc", "dti", "revol_util"]

plot_feature_distributions(df_cls, features)

"""**4. Leakage + Irrelevant Feature Removal**"""

def _cols_with_prefix(df: DataFrame, prefixes: tuple[str, ...]) -> list[str]:
    cols = df.columns
    return [c for c in cols if any(c.startswith(p) for p in prefixes)]


def get_drop_columns(
    df: DataFrame,
    leakage_cols: list[str] | None = None,
    irrelevant_cols: list[str] | None = None,
    proxy_cols: list[str] | None = None,
    explicit_post_issue_extras: list[str] | None = None,
    post_issue_prefixes: tuple[str, ...] = ("hardship_", "settlement_", "debt_settlement_"),
) -> dict:
    if leakage_cols is None:
        leakage_cols = [
            "out_prncp", "out_prncp_inv",
            "total_pymnt", "total_pymnt_inv",
            "total_rec_prncp", "total_rec_int", "total_rec_late_fee",
            "recoveries", "collection_recovery_fee",
            "last_pymnt_d", "last_pymnt_amnt", "next_pymnt_d",
            "last_credit_pull_d",
            "last_fico_range_high", "last_fico_range_low",
        ]

    if irrelevant_cols is None:
        irrelevant_cols = ["member_id", "url", "desc", "title", "emp_title", "zip_code"]

    if proxy_cols is None:
        proxy_cols = ["sub_grade"]

    if explicit_post_issue_extras is None:
        explicit_post_issue_extras = [
            "deferral_term",
            "payment_plan_start_date",
            "orig_projected_additional_accrued_interest",
        ]

    existing = set(df.columns)
    dynamic_cols = _cols_with_prefix(df, post_issue_prefixes)

    drop_leakage = [c for c in leakage_cols if c in existing]
    drop_dynamic = [c for c in dynamic_cols if c in existing]
    drop_extras = [c for c in explicit_post_issue_extras if c in existing]
    drop_irrel = [c for c in irrelevant_cols if c in existing]
    drop_proxy = [c for c in proxy_cols if c in existing]

    all_drop = sorted(set(drop_leakage + drop_dynamic + drop_extras + drop_irrel + drop_proxy))

    return {
        "leakage": drop_leakage,
        "dynamic": drop_dynamic,
        "extras": drop_extras,
        "irrelevant": drop_irrel,
        "proxy": drop_proxy,
        "all": all_drop,
    }


def drop_columns(df: DataFrame, drop_report: dict) -> DataFrame:
    cols_to_drop = drop_report.get("all", [])
    return df.drop(*cols_to_drop) if cols_to_drop else df


def print_drop_report(df_before: DataFrame, drop_report: dict, df_after: DataFrame) -> None:
    cols_before = len(df_before.columns)
    cols_after = len(df_after.columns)

    print("\n================ COLUMN DROPS ================")
    print(f"Before -> Columns: {cols_before}")
    print(f"After  -> Columns: {cols_after}")
    print(f"Columns dropped: {cols_before - cols_after}")

    print("\nA) Leakage:", len(drop_report["leakage"]))
    print("B) Post-issue (prefix):", len(drop_report["dynamic"]))
    print("B2) Post-issue (explicit):", len(drop_report["extras"]))
    print("C) Irrelevant/high-cardinality:", len(drop_report["irrelevant"]))
    print("D) Proxy:", len(drop_report["proxy"]))
    print("TOTAL:", len(drop_report["all"]))


# call
drop_report = get_drop_columns(df_cls)
df_clean = drop_columns(df_cls, drop_report)
print_drop_report(df_cls, drop_report, df_clean)

"""**5. Duplicate & Key Sanity Check**"""

def duplicate_key_report(df: DataFrame, key_col: str = "id") -> None:
    total_rows = df.count()
    duplicate_full_rows = total_rows - df.distinct().count()

    duplicated_key_values = (
        df.groupBy(key_col)
          .count()
          .filter(F.col("count") > 1)
          .count()
    )

    print("Total rows:", total_rows)
    print("Duplicate full rows:", duplicate_full_rows)
    print("Number of duplicated id values:", duplicated_key_values)


# call
duplicate_key_report(df_clean, "id")

"""**6. Type Correction + Date Parsing + Structured Feature Engineering**"""

def engineer_features(df: DataFrame) -> DataFrame:
    df2 = (
        df.withColumn("issue_date", F.to_date(F.col("issue_d"), "MMM-yyyy"))
          .withColumn("earliest_cr_line_date", F.to_date(F.col("earliest_cr_line"), "MMM-yyyy"))
          .withColumn("sec_app_earliest_cr_line_date", F.to_date(F.col("sec_app_earliest_cr_line"), "MMM-yyyy"))
          .withColumn("term_months", F.regexp_extract(F.col("term"), r"(\d+)", 1).cast("int"))
          .withColumn(
              "emp_length_years",
              F.when(F.col("emp_length").isNull(), F.lit(None).cast("int"))
               .when(F.col("emp_length") == "10+ years", F.lit(10))
               .when(F.col("emp_length") == "< 1 year", F.lit(0))
               .otherwise(F.regexp_extract(F.col("emp_length"), r"(\d+)", 1).cast("int"))
          )
          .withColumn(
              "credit_hist_months",
              F.months_between(F.col("issue_date"), F.col("earliest_cr_line_date"))
          )
          .withColumn(
              "fico_avg",
              (F.col("fico_range_low") + F.col("fico_range_high")) / 2
          )
          .withColumn(
              "loan_income_ratio",
              F.when(F.col("annual_inc") > 0, F.col("loan_amnt") / F.col("annual_inc")).otherwise(F.lit(None))
          )
          .withColumn(
              "installment_income_ratio",
              F.when(F.col("annual_inc") > 0, F.col("installment") / F.col("annual_inc")).otherwise(F.lit(None))
          )
          .drop(
              "issue_d",
              "earliest_cr_line",
              "sec_app_earliest_cr_line",
              "earliest_cr_line_date",
              "sec_app_earliest_cr_line_date",
              "term",
              "emp_length",
              "fico_range_low",
              "fico_range_high",
          )
    )
    return df2


def audit_string_columns(df: DataFrame) -> list[str]:
    return [f.name for f in df.schema.fields if isinstance(f.dataType, StringType)]


def quality_check_nulls(df: DataFrame, cols: list[str]) -> dict[str, tuple[int, float]]:
    total = df.count()
    out = {}
    for c in cols:
        n = df.filter(F.col(c).isNull()).count()
        pct = (n / total) * 100 if total else 0.0
        out[c] = (n, pct)
    return out


def show_engineered_summaries(df: DataFrame) -> None:
    df.select(
        "fico_avg",
        "loan_income_ratio",
        "installment_income_ratio",
        "credit_hist_months",
    ).describe().show()

    df.select(
        "issue_date",
        "term_months",
        "emp_length_years",
        "credit_hist_months",
        "fico_avg",
        "loan_income_ratio",
        "installment_income_ratio",
    ).show(5, truncate=False)


# call
string_cols = audit_string_columns(df_clean)
print("Number of string columns:", len(string_cols))
print(string_cols)

df_clean = engineer_features(df_clean)

null_report = quality_check_nulls(
    df_clean,
    ["issue_date", "term_months", "emp_length_years"],
)
for c, (n, pct) in null_report.items():
    print(f"{c}: {n} ({pct:.4f}%)")

show_engineered_summaries(df_clean)

print("Done!")

def plot_default_rate_by_term(df: DataFrame) -> None:
    term_pd = (
        df.groupBy("term_months")
          .agg(F.mean("label").alias("default_rate"))
          .orderBy("term_months")
          .toPandas()
    )

    plt.figure(figsize=(4, 3))
    plt.bar(term_pd["term_months"].astype(str),
            term_pd["default_rate"] * 100)
    plt.title("Default Rate by Loan Term")
    plt.xlabel("Term (months)")
    plt.ylabel("Default Rate (%)")
    plt.tight_layout()
    plt.show()


# call
plot_default_rate_by_term(df_clean)

def plot_default_rate_by_fico(df: DataFrame, bin_size: int = 20) -> None:
    fico_pd = (
        df.withColumn("fico_bin", F.floor(F.col("fico_avg") / bin_size) * bin_size)
          .groupBy("fico_bin")
          .agg(F.mean("label").alias("default_rate"))
          .orderBy("fico_bin")
          .toPandas()
    )

    plt.figure(figsize=(4, 3))
    plt.plot(fico_pd["fico_bin"], fico_pd["default_rate"] * 100)
    plt.title("Default Rate by FICO Score")
    plt.xlabel("FICO Score (binned)")
    plt.ylabel("Default Rate (%)")
    plt.tight_layout()
    plt.show()


# call
plot_default_rate_by_fico(df_clean)

"""**7. Missingness + constants + checking boxplots and distributions + simple validity bounds**"""

from pyspark.sql.types import (
    IntegerType, LongType, FloatType, DoubleType, DecimalType
)

def get_numeric_columns(df):
    numeric_types = (IntegerType, LongType, FloatType, DoubleType, DecimalType)

    numeric_cols = [
        field.name for field in df.schema.fields
        if isinstance(field.dataType, numeric_types)
    ]

    return numeric_cols

def plot_all_numeric_distributions(
    df,
    sample_fraction=0.05,
    bins=40,
    max_cols_per_fig=4,
    figsize=(7,5),
    dropna=True
):

    numeric_cols = get_numeric_columns(df)

    sdf = df.select(numeric_cols)

    if dropna:
        sdf = sdf.dropna()

    pdf = sdf.sample(fraction=sample_fraction).toPandas()

    cols = numeric_cols
    total = len(cols)

    for start in range(0, total, max_cols_per_fig):
        subset = cols[start:start + max_cols_per_fig]

        plt.figure(figsize=(14,10))

        for i, col in enumerate(subset, 1):
            plt.subplot(2, 2, i)
            sns.histplot(pdf[col], bins=bins)
            plt.title(f"Distribution of {col}")
            plt.xlabel("")
            plt.ylabel("")

        plt.tight_layout()
        plt.show()

def plot_all_numeric_boxplots(
    df,
    sample_fraction=0.05,
    max_cols_per_fig=4,
    figsize=(7,5),
    dropna=True
):

    numeric_cols = get_numeric_columns(df)

    sdf = df.select(numeric_cols)

    if dropna:
        sdf = sdf.dropna()

    pdf = sdf.sample(fraction=sample_fraction).toPandas()

    cols = numeric_cols
    total = len(cols)

    for start in range(0, total, max_cols_per_fig):
        subset = cols[start:start + max_cols_per_fig]

        plt.figure(figsize=(14,10))

        for i, col in enumerate(subset, 1):
            plt.subplot(2, 2, i)
            sns.boxplot(x=pdf[col])
            plt.title(f"Boxplot of {col}")
            plt.xlabel("")

        plt.tight_layout()
        plt.show()

# calls
numeric_cols = get_numeric_columns(df_clean)

plot_all_numeric_distributions(
    df=df_clean,
    features=numeric_cols,
    sample_fraction=0.05
)

plot_all_numeric_boxplots(
    df=df_clean,
    features=numeric_cols,
    sample_fraction=0.05
)

def get_categorical_columns(df):
    categorical_cols = [
        field.name for field in df.schema.fields
        if isinstance(field.dataType, (StringType, BooleanType))
    ]
    return categorical_cols

def check_categorical_distribution(df, categorical_cols):

    for col in categorical_cols:
        print(f"\nColumn: {col}")

        df.groupBy(col) \
          .count() \
          .orderBy("count", ascending=False) \
          .show(truncate=False)

# calls
categorical_cols = get_categorical_columns(df_clean)

check_categorical_distribution(df_clean, categorical_cols)

def clean_missingness_and_bounds(
    spark: SparkSession,
    df: DataFrame,
    missing_threshold: float = 0.85,
    imbalance_threshold: float = 0.995,
    protect_cols: tuple[str, ...] = ("label", "id"),
    show_top_missing: int = 20,
) -> tuple[DataFrame, dict]:
    n = df.count()

    null_counts = df.select(
        [F.sum(F.col(c).isNull().cast("int")).alias(c) for c in df.columns]
    ).collect()[0].asDict()

    missing_summary = (
        spark.createDataFrame(
            [(c, int(null_counts[c]), float(null_counts[c]) / n if n else 0.0) for c in df.columns],
            ["column", "null_count", "null_pct"],
        )
        .orderBy(F.desc("null_pct"))
    )

    if show_top_missing and show_top_missing > 0:
        missing_summary.show(show_top_missing, truncate=False)

    sparse_cols = (
        missing_summary.filter((F.col("null_pct") > missing_threshold) & (~F.col("column").isin(list(protect_cols))))
        .select("column")
        .rdd.flatMap(lambda x: x)
        .collect()
    )

    df2 = df.drop(*sparse_cols) if sparse_cols else df

    numeric_cols = [
        f.name for f in df2.schema.fields
        if isinstance(f.dataType, NumericType) and f.name not in protect_cols
    ]

    agg_exprs = []
    for c in numeric_cols:
        agg_exprs.append(F.min(c).alias(f"{c}__min"))
        agg_exprs.append(F.max(c).alias(f"{c}__max"))

    stats = df2.agg(*agg_exprs).collect()[0].asDict() if agg_exprs else {}
    constant_numeric = [c for c in numeric_cols if stats.get(f"{c}__min") == stats.get(f"{c}__max")]

    df3 = df2.drop(*constant_numeric) if constant_numeric else df2

    string_cols = [
        f.name for f in df3.schema.fields
        if isinstance(f.dataType, StringType) and f.name not in protect_cols
    ]

    near_constant_string = []
    for c in string_cols:
        total_non_null = df3.where(F.col(c).isNotNull()).count()
        if total_non_null == 0:
            continue

        top = (
            df3.where(F.col(c).isNotNull())
               .groupBy(c).count()
               .orderBy(F.desc("count"))
               .limit(1)
               .collect()
        )
        if not top:
            continue

        if (top[0]["count"] / total_non_null) > imbalance_threshold:
            near_constant_string.append(c)

    df4 = df3.drop(*near_constant_string) if near_constant_string else df3

    df5 = (
        df4.withColumn(
            "loan_income_ratio",
            F.when((F.col("annual_inc") < 1000) | (F.col("loan_income_ratio") > 10), 10)
             .otherwise(F.col("loan_income_ratio")),
        )
        .withColumn(
            "installment_income_ratio",
            F.when((F.col("annual_inc") < 1000) | (F.col("installment_income_ratio") > 1), 1)
             .otherwise(F.col("installment_income_ratio")),
        )
        .withColumn("dti", F.when(F.col("dti") < 0, 0).otherwise(F.col("dti")))
        .withColumn(
            "revol_util",
            F.when(F.col("revol_util") < 0, 0)
             .when(F.col("revol_util") > 100, 100)
             .otherwise(F.col("revol_util")),
        )
        .withColumn(
            "credit_hist_months",
            F.when(F.col("credit_hist_months") < 0, None).otherwise(F.col("credit_hist_months")),
        )
        .withColumn(
            "fico_avg",
            F.when((F.col("fico_avg") < 300) | (F.col("fico_avg") > 850), None).otherwise(F.col("fico_avg")),
        )
    )

    for c in ["il_util", "bc_util", "all_util", "percent_bc_gt_75"]:
        if c in df5.columns:
            df5 = df5.withColumn(
                c,
                F.when(F.col(c) < 0, None)
                 .when(F.col(c) > 150, 150)
                 .otherwise(F.col(c)),
            )

    report = {
        "rows": n,
        "dropped_sparse": sparse_cols,
        "dropped_constant_numeric": constant_numeric,
        "dropped_near_constant_string": near_constant_string,
        "columns_before": len(df.columns),
        "columns_after": len(df5.columns),
    }

    return df5, report


# call
df_clean, report = clean_missingness_and_bounds(spark, df_clean)
print("Done!")

def plot_loan_income_ratio_distribution(
    df: DataFrame,
    sample_fraction: float = 0.05,
    bins: int = 50,
) -> None:
    ratio_pd = (
        df.select("loan_income_ratio")
          .sample(sample_fraction)
          .toPandas()
    )

    plt.figure(figsize=(4, 3))
    plt.hist(ratio_pd["loan_income_ratio"], bins=bins)
    plt.title("Distribution of Loan-Income Ratio (Capped)")
    plt.xlabel("Loan-Income Ratio")
    plt.ylabel("Frequency")
    plt.tight_layout()
    plt.show()


# call
plot_loan_income_ratio_distribution(df_clean)

"""**8. Correlation Analysis & Redundant Feature Identification**"""

def correlation_analysis(
    spark,
    df: DataFrame,
    target_col: str = "int_rate",
    label_col: str = "label",
    top_n: int = 10,
    threshold: float = 0.90,
) -> None:

    numeric_cols = [
        f.name for f in df.schema.fields
        if isinstance(f.dataType, NumericType)
        and f.name not in [target_col, label_col]
    ]

    df_corr = df.select(numeric_cols).dropna()

    assembler = VectorAssembler(
        inputCols=numeric_cols,
        outputCol="features",
        handleInvalid="skip",
    )

    df_vec = assembler.transform(df_corr).select("features")
    corr_row = Correlation.corr(df_vec, "features", "pearson").head()
    corr_np = np.array(corr_row[0].toArray())
    corr_df = pd.DataFrame(corr_np, index=numeric_cols, columns=numeric_cols)

    figsize = (max(10, len(numeric_cols) * 0.35),
               max(8, len(numeric_cols) * 0.35))

    plt.figure(figsize=figsize)
    plt.imshow(corr_np)
    plt.title("Pearson Correlation Matrix")
    plt.xticks(range(len(numeric_cols)), numeric_cols, rotation=90, fontsize=6)
    plt.yticks(range(len(numeric_cols)), numeric_cols, fontsize=6)
    plt.colorbar()
    plt.tight_layout()
    plt.show()

    avg_abs = np.mean(np.abs(corr_np - np.eye(corr_np.shape[0])), axis=1)
    top_idx = np.argsort(-avg_abs)[:top_n]
    top_cols = [numeric_cols[i] for i in top_idx]
    sub = corr_df.loc[top_cols, top_cols].values

    plt.figure(figsize=(7, 6))
    plt.imshow(sub)

    for i in range(top_n):
        for j in range(top_n):
            plt.text(j, i, f"{sub[i, j]:.2f}", ha="center", va="center", color="black", fontsize=7)

    plt.title(f"Pearson Correlation Matrix (Top {top_n})")
    plt.xticks(range(top_n), top_cols, rotation=90, fontsize=7)
    plt.yticks(range(top_n), top_cols, fontsize=7)
    plt.colorbar()
    plt.tight_layout()
    plt.show()

    pairs = []
    for i in range(len(numeric_cols)):
        for j in range(i + 1, len(numeric_cols)):
            r = float(corr_np[i, j])
            if abs(r) >= threshold:
                pairs.append((numeric_cols[i], numeric_cols[j], r))

    pairs_sorted = sorted(pairs, key=lambda x: abs(x[2]), reverse=True)

    print(f"Highly correlated feature pairs (|r| >= {threshold}):", len(pairs_sorted))
    for a, b, r in pairs_sorted[:30]:
        print(f"{a:30s}  vs  {b:30s}  corr={r:.4f}")

    print("Done!")


# call
correlation_analysis(spark, df_clean)

def drop_correlated_columns(df: DataFrame, cols_to_drop: list[str]) -> DataFrame:
    existing = [c for c in cols_to_drop if c in df.columns]
    return df.drop(*existing) if existing else df


# call
cols_to_drop_corr = [
    "funded_amnt",
    "funded_amnt_inv",
    "installment",
    "num_rev_tl_bal_gt_0",
    "num_sats",
    "tot_cur_bal",
    "installment_income_ratio",
    "total_bal_il",
    "total_il_high_credit_limit",
    "mo_sin_old_rev_tl_op",
]

df_clean = drop_correlated_columns(df_clean, cols_to_drop_corr)

print("Columns after correlation drop:", len(df_clean.columns))

def dataset_column_summary(
    df: DataFrame,
    classification_target: str = "label",
    regression_target: str = "int_rate",
) -> None:

    numeric_cols_all = [
        f.name for f in df.schema.fields
        if isinstance(f.dataType, NumericType)
    ]

    categorical_cols = [
        f.name for f in df.schema.fields
        if isinstance(f.dataType, StringType)
    ]

    targets_present = [
        c for c in [classification_target, regression_target]
        if c in df.columns
    ]

    print("Total columns:", len(df.columns))
    print("Total numeric columns (including targets):", len(numeric_cols_all))
    print("Total categorical columns:", len(categorical_cols))
    print("Targets present in dataset:", targets_present)
    print("\nCategorical column names:")
    print(categorical_cols)


# call
dataset_column_summary(df_clean)

df_clean.groupBy("initial_list_status") \
        .count() \
        .orderBy(F.desc("count")) \
        .show()

"""**9. Time-Aware Train/Test Split**"""

def chronological_train_test_split(
    df: DataFrame,
    date_col: str = "issue_date",
    train_frac: float = 0.8,
    drop_cols_after_split: tuple[str, ...] = ("issue_date", "id"),
) -> tuple[DataFrame, DataFrame]:

    if date_col not in df.columns:
        raise ValueError(f"{date_col} column missing")

    w = Window.orderBy(F.col(date_col))
    df_ordered = df.withColumn("row_num", F.row_number().over(w))

    total = df_ordered.count()
    split_index = int(total * train_frac)

    train = df_ordered.filter(F.col("row_num") <= split_index).drop("row_num")
    test = df_ordered.filter(F.col("row_num") > split_index).drop("row_num")

    cols_to_remove = [c for c in drop_cols_after_split if c in train.columns]
    if cols_to_remove:
        train = train.drop(*cols_to_remove)
        test = test.drop(*cols_to_remove)

    return train, test


def show_split_stats(
    train: DataFrame,
    test: DataFrame,
    date_col: str = "issue_date",
) -> None:
    print("Train rows:", train.count())
    print("Test rows:", test.count())

    if date_col in train.columns:
        print("\nTrain date range:")
        train.select(F.min(date_col).alias("min"), F.max(date_col).alias("max")).show()

    if date_col in test.columns:
        print("Test date range:")
        test.select(F.min(date_col).alias("min"), F.max(date_col).alias("max")).show()

    print("\nFinal Train columns:", len(train.columns))
    print("Final Test columns:", len(test.columns))


# call
train, test = chronological_train_test_split(df_clean)
print("Done!")

def plot_train_test_label_distribution(
    train: DataFrame,
    test: DataFrame,
) -> None:

    train_pd = train.groupBy("label").count().orderBy("label").toPandas()
    test_pd = test.groupBy("label").count().orderBy("label").toPandas()

    plt.figure(figsize=(4, 3))

    plt.bar(train_pd["label"] - 0.15,
            train_pd["count"],
            width=0.3,
            label="Train")

    plt.bar(test_pd["label"] + 0.15,
            test_pd["count"],
            width=0.3,
            label="Test")

    plt.title("Label Distribution (Train vs Test)")
    plt.xlabel("Label (0=Non-Default, 1=Default)")
    plt.ylabel("Count")
    plt.legend()
    plt.show()


# call
plot_train_test_label_distribution(train, test)

def plot_train_test_int_rate_distribution(
    train: DataFrame,
    test: DataFrame,
    sample_fraction: float = 0.1,
    bins: int = 30,
) -> None:

    train_pd = (
        train.select("int_rate")
             .sample(fraction=sample_fraction)
             .toPandas()
    )

    test_pd = (
        test.select("int_rate")
            .sample(fraction=sample_fraction)
            .toPandas()
    )

    plt.figure(figsize=(4, 3))
    plt.hist(train_pd["int_rate"], bins=bins, alpha=0.6, label="Train")
    plt.hist(test_pd["int_rate"], bins=bins, alpha=0.6, label="Test")
    plt.title("Interest Rate Distribution (Train vs Test)")
    plt.xlabel("Interest Rate")
    plt.ylabel("Frequency")
    plt.legend()
    plt.show()


# call
plot_train_test_int_rate_distribution(train, test)

train.groupBy("label").count().show()
test.groupBy("label").count().show()

rows = train.count()
cols = len(train.columns)

print(f"Shape of train: ({rows}, {cols})")

rows = test.count()
cols = len(test.columns)

print(f"Shape of train: ({rows}, {cols})")

"""**10. Missing Values Imputataion**"""

def train_fitted_imputation(
    train: DataFrame,
    test: DataFrame,
    classification_target: str = "label",
    regression_target: str = "int_rate",
    unknown_token: str = "Unknown",
) -> tuple[DataFrame, DataFrame]:
    numeric_cols_all = [
        f.name for f in train.schema.fields
        if isinstance(f.dataType, NumericType)
    ]
    cat_cols_all = [
        f.name for f in train.schema.fields
        if isinstance(f.dataType, StringType)
    ]

    numeric_feature_cols = [
        c for c in numeric_cols_all
        if c not in [classification_target, regression_target]
    ]

    train_null_counts = train.select(
        [F.sum(F.col(c).isNull().cast("int")).alias(c) for c in train.columns]
    ).collect()[0].asDict()

    numeric_missing = [c for c in numeric_feature_cols if train_null_counts.get(c, 0) > 0]
    cat_missing = [c for c in cat_cols_all if train_null_counts.get(c, 0) > 0]

    mths_since_missing = [c for c in numeric_missing if c.startswith("mths_since_")]
    continuous_missing = [c for c in numeric_missing if c not in mths_since_missing]

    medians = {}
    if continuous_missing:
        medians = train.select(
            [F.expr(f"percentile_approx({c}, 0.5)").alias(c) for c in continuous_missing]
        ).collect()[0].asDict()

    mths_fill = {}
    if mths_since_missing:
        max_vals = train.select([F.max(F.col(c)).alias(c) for c in mths_since_missing]).collect()[0].asDict()
        mths_fill = {
            c: float(max_vals[c]) + 1.0
            for c in mths_since_missing
            if max_vals.get(c) is not None
        }

    def apply(df: DataFrame) -> DataFrame:
        out = df

        for c, mv in medians.items():
            if mv is not None and c in out.columns:
                out = out.withColumn(c, F.when(F.col(c).isNull(), F.lit(mv)).otherwise(F.col(c)))

        for c, fv in mths_fill.items():
            if fv is not None and c in out.columns:
                out = out.withColumn(c, F.when(F.col(c).isNull(), F.lit(fv)).otherwise(F.col(c)))

        for c in cat_missing:
            if c in out.columns:
                out = out.withColumn(c, F.when(F.col(c).isNull(), F.lit(unknown_token)).otherwise(F.col(c)))

        return out

    return apply(train), apply(test)


# call
train_imp, test_imp = train_fitted_imputation(train, test)
print("Done!")

"""**11. Saving the Dataset**"""

train_path = "/content/drive/MyDrive/DDAM/train_final"
test_path  = "/content/drive/MyDrive/DDAM/test_final"

train_imp.write.mode("overwrite").option("header", True).csv(train_path)
test_imp.write.mode("overwrite").option("header", True).csv(test_path)

print("Train and Test datasets saved successfully.")

train_path = "/content/drive/MyDrive/DDAM/train_final_parquet"
test_path  = "/content/drive/MyDrive/DDAM/test_final_parquet"

train_imp.write.mode("overwrite").parquet(train_path)
test_imp.write.mode("overwrite").parquet(test_path)

print("Train and Test saved as Parquet.")