# -*- coding: utf-8 -*-
"""Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wQYEDdo6J-wrMtseAT5pshIpGFJQRVAs

**0. Moutning GDrive**
"""

from google.colab import drive
drive.mount('/content/drive')

"""**1. Importing Required Libraries**"""

import random
import itertools
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, when

from pyspark.ml.feature import (
    StringIndexer,
    OneHotEncoder,
    VectorAssembler,
    VectorSlicer,
    StandardScaler
)

from pyspark.ml.classification import (
    LogisticRegression,
    GBTClassifier,
    RandomForestClassifier
)

from pyspark.ml.evaluation import BinaryClassificationEvaluator
from pyspark.ml.tuning import CrossValidator

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    roc_curve,
    auc,
    ConfusionMatrixDisplay,
    precision_score,
    recall_score,
    f1_score
)

"""**2. StringIndexer+OHE+VectorAssembler**"""

spark = SparkSession.builder.appName("Classification_Preprocessing").getOrCreate()

train_path = "/content/drive/MyDrive/DDAM/train.csv"
test_path  = "/content/drive/MyDrive/DDAM/test.csv"

train_df = spark.read.csv(train_path, header=True, inferSchema=True)
test_df  = spark.read.csv(test_path, header=True, inferSchema=True)

print("Train rows:", train_df.count())
print("Train columns:", len(train_df.columns))
print("Test rows:", test_df.count())
print("Test columns:", len(test_df.columns))

train_df = train_df.drop("int_rate")
test_df  = test_df.drop("int_rate")

label_col = "label"

categorical_cols = [
    "grade",
    "home_ownership",
    "verification_status",
    "purpose",
    "addr_state",
    "initial_list_status",
    "application_type",
    "disbursement_method"
]

excluded_cols = set(categorical_cols + [label_col])
numerical_cols = [c for c in train_df.columns if c not in excluded_cols]

print("Numerical columns:", len(numerical_cols))
print("Categorical columns:", len(categorical_cols))

train_indexed_df = train_df
test_indexed_df = test_df

indexer_models = {}
index_cols = []

for c in categorical_cols:
    idx_col = c + "_idx"

    indexer = StringIndexer(
        inputCol=c,
        outputCol=idx_col,
        handleInvalid="keep"
    )

    model = indexer.fit(train_indexed_df)

    train_indexed_df = model.transform(train_indexed_df)
    test_indexed_df = model.transform(test_indexed_df)

    indexer_models[c] = model
    index_cols.append(idx_col)

ohe_cols = [c + "_ohe" for c in categorical_cols]

encoder = OneHotEncoder(
    inputCols=index_cols,
    outputCols=ohe_cols,
    handleInvalid="keep",
    dropLast=True
)

encoder_model = encoder.fit(train_indexed_df)

train_encoded_df = encoder_model.transform(train_indexed_df)
test_encoded_df = encoder_model.transform(test_indexed_df)


assembler_input_cols = numerical_cols + ohe_cols

assembler = VectorAssembler(
    inputCols=assembler_input_cols,
    outputCol="features"
)

train_final_df = assembler.transform(train_encoded_df)
test_final_df  = assembler.transform(test_encoded_df)

print("Train feature vector size:", train_final_df.select("features").first()[0].size)
print("Test feature vector size:", test_final_df.select("features").first()[0].size)


expanded_feature_names = []
expanded_feature_names.extend(numerical_cols)

for c, ohe_col in zip(categorical_cols, ohe_cols):
    vec_size = train_final_df.select(ohe_col).first()[0].size
    labels = indexer_models[c].labels

    for i in range(vec_size):
        if i < len(labels):
            expanded_feature_names.append(f"{c}__{labels[i]}")
        else:
            expanded_feature_names.append(f"{c}__INVALID_OR_UNSEEN")

print("Total expanded feature names:", len(expanded_feature_names))
print("Sanity check vector size:", train_final_df.select("features").first()[0].size)

"""**3. Feature Selection by using Random Forest**"""

feature_vector_size = train_final_df.select("features").first()[0].size
print("Vector size:", feature_vector_size)
print("Expanded feature names:", len(expanded_feature_names))


rf = RandomForestClassifier(
    labelCol="label",
    featuresCol="features",
    numTrees=100,
    maxDepth=10,
    seed=42
)

rf_model = rf.fit(train_final_df)

rf_importances = np.array(rf_model.featureImportances.toArray())

rf_df = pd.DataFrame({
    "feature": expanded_feature_names,
    "importance": rf_importances
})

rf_df = rf_df.sort_values("importance", ascending=False).reset_index(drop=True)

print("All features by Random Forest importance:")
print(rf_df.to_string(index=False))

top_10_rf = rf_df.head(10)

plt.figure(figsize=(10,6))
plt.barh(top_10_rf["feature"][::-1], top_10_rf["importance"][::-1])
plt.xlabel("Feature Importance Score")
plt.ylabel("Feature")
plt.title("Top 10 Random Forest Feature Importance")
plt.tight_layout()
plt.show()

threshold = 0.002

selected_features = rf_df[rf_df["importance"] >= threshold]["feature"].tolist()

print("Selected feature count:", len(selected_features))
print(selected_features)

threshold = 0.002

selected_rf_df = rf_df[rf_df["importance"] >= threshold].copy()

print("Selected features based on threshold:")
print(selected_rf_df.to_string(index=False))

print("\nNumber of selected features:", len(selected_rf_df))

selected_feature_names = selected_rf_df["feature"].tolist()

print("\nSelected feature names:")
for f in selected_feature_names:
    print(f)

feature_name_to_index = {name: idx for idx, name in enumerate(expanded_feature_names)}

selected_feature_indices = [feature_name_to_index[name] for name in selected_feature_names]

selected_feature_indices = sorted(selected_feature_indices)

print("\nSelected feature indices:")
print(selected_feature_indices)

print("\nNumber of selected indices:", len(selected_feature_indices))

slicer = VectorSlicer(
    inputCol="features",
    outputCol="selected_features",
    indices=selected_feature_indices
)

train_selected_df = slicer.transform(train_final_df)
test_selected_df = slicer.transform(test_final_df)

print("Original train feature size:", train_final_df.select("features").first()[0].size)
print("Reduced train feature size:", train_selected_df.select("selected_features").first()[0].size)

print("Original test feature size:", test_final_df.select("features").first()[0].size)
print("Reduced test feature size:", test_selected_df.select("selected_features").first()[0].size)

train_model_df = train_selected_df.select(label_col, "selected_features")
test_model_df = test_selected_df.select(label_col, "selected_features")

print("Train model dataframe:")
train_model_df.show(5, truncate=False)

print("Test model dataframe:")
test_model_df.show(5, truncate=False)

scaler = StandardScaler(
    inputCol="selected_features",
    outputCol="scaled_features",
    withStd=True,
    withMean=False
)

scaler_model = scaler.fit(train_model_df)

train_model_df = scaler_model.transform(train_model_df)
test_model_df  = scaler_model.transform(test_model_df)

print("Scaled feature vector size:", train_model_df.select("scaled_features").first()[0].size)

train_model_df.write.mode("overwrite").parquet(
    "/content/drive/MyDrive/DDAM/train_selected.parquet"
)

test_model_df.write.mode("overwrite").parquet(
    "/content/drive/MyDrive/DDAM/test_selected.parquet"
)

print("Datasets saved successfully.")

from pyspark.sql import SparkSession

spark = SparkSession.builder \
    .appName("DDAM Model") \
    .getOrCreate()

train_model_df = spark.read.parquet("/content/drive/MyDrive/DDAM/train_selected.parquet")
test_model_df  = spark.read.parquet("/content/drive/MyDrive/DDAM/test_selected.parquet")

"""**4. Modeling**

**i) Logistic Regression**
"""

print("Train rows:", train_model_df.count())
print("Test rows:", test_model_df.count())
print("Train feature size:", train_model_df.select("selected_features").first()[0].size)
print("Test feature size:", test_model_df.select("selected_features").first()[0].size)

sample_frac = 0.20
seed = 42

train_tune_df = train_model_df.sampleBy(
    "label",
    fractions={0: sample_frac, 1: sample_frac},
    seed=seed
)

print("Tuning subset rows:", train_tune_df.count())
train_tune_df.groupBy("label").count().show()

label_counts = train_model_df.groupBy("label").count().collect()
count_map = {int(r["label"]): r["count"] for r in label_counts}

count_0 = count_map[0]
count_1 = count_map[1]
total = count_0 + count_1

weight_0 = total / (2.0 * count_0)
weight_1 = total / (2.0 * count_1)

print("Class 0 count:", count_0, "| weight:", weight_0)
print("Class 1 count:", count_1, "| weight:", weight_1)

train_weighted_df = train_model_df.withColumn(
    "classWeight",
    when(col("label") == 0, weight_0).otherwise(weight_1)
)

train_tune_weighted_df = train_tune_df.withColumn(
    "classWeight",
    when(col("label") == 0, weight_0).otherwise(weight_1)
)

def build_random_param_maps(lr, n_samples=12, seed=42):
    random.seed(seed)

    param_space = {
        "regParam": [0.0, 0.001, 0.01, 0.05, 0.1],
        "elasticNetParam": [0.0, 0.25, 0.5, 0.75, 1.0],
        "maxIter": [30, 50, 80, 120],
        "threshold": [0.35, 0.4, 0.45, 0.5]
    }

    all_combos = list(itertools.product(
        param_space["regParam"],
        param_space["elasticNetParam"],
        param_space["maxIter"],
        param_space["threshold"]
    ))

    sampled = random.sample(all_combos, k=min(n_samples, len(all_combos)))

    param_maps = []
    for regParam, elasticNetParam, maxIter, threshold in sampled:
        pm = {
            lr.regParam: regParam,
            lr.elasticNetParam: elasticNetParam,
            lr.maxIter: maxIter,
            lr.threshold: threshold
        }
        param_maps.append(pm)

    return param_maps

def tune_and_train_lr(train_tune_input_df, train_full_input_df, use_weights=False, n_random=12, seed=42):
    if use_weights:
        lr = LogisticRegression(
            labelCol="label",
            featuresCol="selected_features",
            weightCol="classWeight"
        )
    else:
        lr = LogisticRegression(
            labelCol="label",
            featuresCol="selected_features"
        )

    param_maps = build_random_param_maps(lr, n_samples=n_random, seed=seed)

    evaluator = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderROC"
    )

    cv = CrossValidator(
        estimator=lr,
        estimatorParamMaps=param_maps,
        evaluator=evaluator,
        numFolds=3,
        seed=seed,
        parallelism=2
    )

    cv_model = cv.fit(train_tune_input_df)
    best_lr_model = cv_model.bestModel

    best_params = {
        "regParam": best_lr_model.getRegParam(),
        "elasticNetParam": best_lr_model.getElasticNetParam(),
        "maxIter": best_lr_model.getMaxIter(),
        "threshold": best_lr_model.getThreshold()
    }

    print("\nBest parameters:")
    print(best_params)

    if use_weights:
        final_lr = LogisticRegression(
            labelCol="label",
            featuresCol="selected_features",
            weightCol="classWeight",
            regParam=best_params["regParam"],
            elasticNetParam=best_params["elasticNetParam"],
            maxIter=best_params["maxIter"],
            threshold=best_params["threshold"]
        )
    else:
        final_lr = LogisticRegression(
            labelCol="label",
            featuresCol="selected_features",
            regParam=best_params["regParam"],
            elasticNetParam=best_params["elasticNetParam"],
            maxIter=best_params["maxIter"],
            threshold=best_params["threshold"]
        )

    final_model = final_lr.fit(train_full_input_df)

    return final_model, best_params

def evaluate_lr_model(model, test_input_df, title_prefix="Logistic Regression"):
    preds = model.transform(test_input_df).select("label", "prediction", "probability", "rawPrediction")

    evaluator_roc = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderROC"
    )

    evaluator_pr = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderPR"
    )

    auc_roc = evaluator_roc.evaluate(preds)
    auc_pr = evaluator_pr.evaluate(preds)

    pred_pd = preds.toPandas()

    y_true = pred_pd["label"].astype(int).values
    y_pred = pred_pd["prediction"].astype(int).values
    y_score = pred_pd["probability"].apply(lambda v: float(v[1])).values

    print(f"\n{title_prefix} - ROC-AUC: {auc_roc:.4f}")
    print(f"{title_prefix} - PR-AUC:  {auc_pr:.4f}")

    report = classification_report(
        y_true,
        y_pred,
        target_names=["non-default (0)", "default (1)"],
        digits=4,
        zero_division=0
    )

    print(f"\n{title_prefix} - Classification Report:\n")
    print(report)


    fpr, tpr, _ = roc_curve(y_true, y_score)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(4, 3))
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"{title_prefix} ROC Curve")
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.show()

    cm = confusion_matrix(y_true, y_pred)

    fig, ax = plt.subplots(figsize=(4, 3))
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Pred 0", "Pred 1"]
    )
    disp.plot(cmap="Blues", ax=ax, colorbar=False)
    ax.set_title(f"{title_prefix} Confusion Matrix")
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    plt.tight_layout()
    plt.show()

    return {
        "auc_roc": auc_roc,
        "auc_pr": auc_pr,
        "classification_report": report
    }

#call
lr_unweighted_model, lr_unweighted_best_params = tune_and_train_lr(
    train_tune_input_df=train_tune_df,
    train_full_input_df=train_model_df,
    use_weights=False,
    n_random=12,
    seed=42
)

unweighted_results = evaluate_lr_model(
    lr_unweighted_model,
    test_model_df,
    title_prefix="LR Unweighted"
)

#call
lr_weighted_model, lr_weighted_best_params = tune_and_train_lr(
    train_tune_input_df=train_tune_weighted_df,
    train_full_input_df=train_weighted_df,
    use_weights=True,
    n_random=12,
    seed=42
)

weighted_results = evaluate_lr_model(
    lr_weighted_model,
    test_model_df,
    title_prefix="LR Weighted"
)

"""**ii) Gradient Boosted Trees**"""

print("Train rows:", train_model_df.count())
print("Test rows:", test_model_df.count())
print("Train feature size:", train_model_df.select("selected_features").first()[0].size)
print("Test feature size:", test_model_df.select("selected_features").first()[0].size)

sample_frac = 0.20
seed = 42

train_tune_df = train_model_df.sampleBy(
    "label",
    fractions={0: sample_frac, 1: sample_frac},
    seed=seed
)

print("Tuning subset rows:", train_tune_df.count())
train_tune_df.groupBy("label").count().show()

def build_random_param_maps_gbt(gbt, n_samples=12, seed=42):
    random.seed(seed)

    param_space = {
        "maxDepth": [3, 5, 7, 9],
        "maxIter": [20, 40, 60, 80],
        "stepSize": [0.05, 0.1, 0.2],
        "subsamplingRate": [0.6, 0.8, 1.0]
    }

    all_combos = list(itertools.product(
        param_space["maxDepth"],
        param_space["maxIter"],
        param_space["stepSize"],
        param_space["subsamplingRate"]
    ))

    sampled = random.sample(all_combos, k=min(n_samples, len(all_combos)))

    param_maps = []

    for maxDepth, maxIter, stepSize, subsamplingRate in sampled:
        pm = {
            gbt.maxDepth: maxDepth,
            gbt.maxIter: maxIter,
            gbt.stepSize: stepSize,
            gbt.subsamplingRate: subsamplingRate
        }
        param_maps.append(pm)

    return param_maps

def tune_and_train_gbt(
    train_tune_input_df,
    train_full_input_df,
    n_random=12,
    seed=42,
    threshold_candidates=[0.20, 0.25, 0.30, 0.35, 0.40, 0.50]
):
    from sklearn.metrics import precision_score, recall_score, f1_score

    gbt = GBTClassifier(
        labelCol="label",
        featuresCol="selected_features",
        seed=seed
    )

    param_maps = build_random_param_maps_gbt(gbt, n_samples=n_random, seed=seed)

    evaluator = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderROC"
    )

    cv = CrossValidator(
        estimator=gbt,
        estimatorParamMaps=param_maps,
        evaluator=evaluator,
        numFolds=3,
        seed=seed,
        parallelism=2
    )

    cv_model = cv.fit(train_tune_input_df)
    best_gbt_model = cv_model.bestModel

    best_params = {
        "maxDepth": best_gbt_model.getMaxDepth(),
        "maxIter": best_gbt_model.getMaxIter(),
        "stepSize": best_gbt_model.getStepSize(),
        "subsamplingRate": best_gbt_model.getSubsamplingRate()
    }


    tune_preds = best_gbt_model.transform(train_tune_input_df).select("label", "probability")
    tune_pd = tune_preds.toPandas()

    y_true = tune_pd["label"].astype(int).values
    y_score = tune_pd["probability"].apply(lambda v: float(v[1])).values

    threshold_results = []

    for thr in threshold_candidates:
        y_pred = (y_score >= thr).astype(int)

        precision = precision_score(y_true, y_pred, zero_division=0)
        recall = recall_score(y_true, y_pred, zero_division=0)
        f1 = f1_score(y_true, y_pred, zero_division=0)

        threshold_results.append({
            "threshold": thr,
            "precision_default": precision,
            "recall_default": recall,
            "f1_default": f1
        })

    threshold_df = pd.DataFrame(threshold_results).sort_values(
        ["f1_default", "recall_default"],
        ascending=False
    ).reset_index(drop=True)

    best_threshold = float(threshold_df.loc[0, "threshold"])

    print("\nBest parameters:")
    print({
        "maxDepth": best_params["maxDepth"],
        "maxIter": best_params["maxIter"],
        "stepSize": best_params["stepSize"],
        "subsamplingRate": best_params["subsamplingRate"],
        "threshold": best_threshold
    })


    final_gbt = GBTClassifier(
        labelCol="label",
        featuresCol="selected_features",
        maxDepth=best_params["maxDepth"],
        maxIter=best_params["maxIter"],
        stepSize=best_params["stepSize"],
        subsamplingRate=best_params["subsamplingRate"],
        seed=seed
    )

    final_model = final_gbt.fit(train_full_input_df)

    return final_model, best_params, best_threshold, threshold_df

def evaluate_gbt_model(
    model,
    test_input_df,
    threshold=0.50,
    title_prefix="Gradient Boosted Trees"
):
    preds = model.transform(test_input_df).select("label", "probability", "rawPrediction")

    evaluator_roc = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderROC"
    )

    evaluator_pr = BinaryClassificationEvaluator(
        labelCol="label",
        rawPredictionCol="rawPrediction",
        metricName="areaUnderPR"
    )

    auc_roc = evaluator_roc.evaluate(preds)
    auc_pr = evaluator_pr.evaluate(preds)

    pred_pd = preds.toPandas()

    y_true = pred_pd["label"].astype(int).values
    y_score = pred_pd["probability"].apply(lambda v: float(v[1])).values
    y_pred = (y_score >= threshold).astype(int)

    print(f"\n{title_prefix} Tuned Threshold = {threshold}")
    print(f"{title_prefix} - ROC-AUC: {auc_roc:.4f}")
    print(f"{title_prefix} - PR-AUC:  {auc_pr:.4f}")

    report = classification_report(
        y_true,
        y_pred,
        target_names=["non-default (0)", "default (1)"],
        digits=4,
        zero_division=0
    )

    print(f"\n{title_prefix} - Classification Report:\n")
    print(report)


    fpr, tpr, _ = roc_curve(y_true, y_score)
    roc_auc = auc(fpr, tpr)

    plt.figure(figsize=(4, 3))
    plt.plot(fpr, tpr, label=f"AUC = {roc_auc:.3f}")
    plt.plot([0, 1], [0, 1], linestyle="--")
    plt.xlabel("False Positive Rate")
    plt.ylabel("True Positive Rate")
    plt.title(f"{title_prefix} ROC Curve")
    plt.legend(loc="lower right")
    plt.tight_layout()
    plt.show()

    cm = confusion_matrix(y_true, y_pred)

    fig, ax = plt.subplots(figsize=(4, 3))
    disp = ConfusionMatrixDisplay(
        confusion_matrix=cm,
        display_labels=["Pred 0", "Pred 1"]
    )
    disp.plot(cmap="Blues", ax=ax, colorbar=False)
    ax.set_title(f"{title_prefix} Confusion Matrix")
    ax.set_xlabel("Predicted Label")
    ax.set_ylabel("True Label")
    plt.tight_layout()
    plt.show()

    return {
        "auc_roc": auc_roc,
        "auc_pr": auc_pr,
        "classification_report": report,
        "threshold": threshold
    }

gbt_model, gbt_best_params, gbt_best_threshold, gbt_threshold_df = tune_and_train_gbt(
    train_tune_input_df=train_tune_df,
    train_full_input_df=train_model_df,
    n_random=12,
    seed=42,
    threshold_candidates=[0.20, 0.25, 0.30, 0.35, 0.40, 0.50]
)

gbt_results = evaluate_gbt_model(
    gbt_model,
    test_model_df,
    threshold=gbt_best_threshold,
    title_prefix="Gradient Boosted Trees"
)

importances = gbt_model.featureImportances.toArray()

attrs = train_model_df.schema["selected_features"].metadata["ml_attr"]["attrs"]

feature_names = []
for k in attrs:
    feature_names += [f["name"] for f in attrs[k]]

feat_imp_df = pd.DataFrame({
    "feature": feature_names,
    "importance": importances
})

feat_imp_df = feat_imp_df.sort_values("importance", ascending=False).head(10)

plt.figure(figsize=(5,3))
plt.barh(feat_imp_df["feature"][::-1], feat_imp_df["importance"][::-1])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 Feature Importance (GBT)")
plt.tight_layout()
plt.show()