# -*- coding: utf-8 -*-
"""Regression-02.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfCdGJZtVXdy3ueU3ml_Vib5FUhL3agH

##1.Mount Drive
"""

from google.colab import drive
drive.mount('/content/drive')

"""##2.Import Libraries"""

import numpy as np
import pandas as pd

from pyspark.sql import SparkSession
from pyspark.sql.functions import col

from pyspark.ml import Pipeline
from pyspark.ml.feature import VectorAssembler, StandardScaler

from pyspark.ml.regression import LinearRegression, GBTRegressor
from pyspark.ml.regression import RandomForestRegressor

from pyspark.ml.tuning import CrossValidator, ParamGridBuilder
from pyspark.ml.evaluation import RegressionEvaluator

import matplotlib.pyplot as plt

import seaborn as sns

"""##3.Enviroment Setup and Dataset Loading


"""

spark = (
    SparkSession.builder
    .appName("LendingClub_Regression")
    .getOrCreate()
)


TRAIN_PATH = "/content/drive/MyDrive/train.csv"
TEST_PATH = "/content/drive/MyDrive/test.csv"


train_df = spark.read.csv(TRAIN_PATH, header=True, inferSchema=True)
test_df = spark.read.csv(TEST_PATH, header=True, inferSchema=True)

print("Train rows:", train_df.count(), "| Columns:", len(train_df.columns))
print("Test rows:", test_df.count(), "| Columns:", len(test_df.columns))

"""#3.1 Dataset Inspection"""

print("Training dataset size:", train_df.count())
print("Test dataset size:", test_df.count())

print("Number of columns:", len(train_df.columns))

train_df.printSchema()

numeric_cols = []
categorical_cols = []

for field in train_df.schema.fields:
    dtype = field.dataType.simpleString()

    if dtype in ["double", "int", "bigint", "float"]:
        numeric_cols.append(field.name)
    else:
        categorical_cols.append(field.name)

print("Number of numeric columns:", len(numeric_cols))
print("Number of categorical columns:", len(categorical_cols))

print("\nNumeric columns:")
print(numeric_cols)

print("\nCategorical columns:")
print(categorical_cols)

print("Predictor columns:\n")

for c in feature_cols:
    print(c)

"""#3.2 Dropping Leakage and Categorical columns"""

categorical_cols = [
    'grade',
    'home_ownership',
    'verification_status',
    'purpose',
    'addr_state',
    'initial_list_status',
    'application_type',
    'disbursement_method'
]

drop_cols = categorical_cols + ['label']

train_df = train_df.drop(*drop_cols)
test_df = test_df.drop(*drop_cols)

print("Dropped columns:")
print(drop_cols)

print("\nUpdated number of columns in training set:", len(train_df.columns))
print("Updated number of columns in test set:", len(test_df.columns))

"""#3.3 Defining target varible"""

LABEL_COL = "int_rate"

feature_cols = [c for c in train_df.columns if c != LABEL_COL]

print("Target column:", LABEL_COL)
print("Number of predictors:", len(feature_cols))

"""#4.Random Forest"""

rf_sample_fraction = 0.20
rf_seed = 42

train_sample_df = train_df.sample(
    withReplacement=False,
    fraction=rf_sample_fraction,
    seed=rf_seed
)

print("Original training rows:", train_df.count())
print("Sampled training rows:", train_sample_df.count())

rf_assembler = VectorAssembler(
    inputCols=feature_cols,
    outputCol="features"
)

train_sample_vec = rf_assembler.transform(
    train_sample_df.select(feature_cols + [LABEL_COL])
).select("features", LABEL_COL)

print("Feature vector created successfully for RF feature selection.")

rf_selector = RandomForestRegressor(
    featuresCol="features",
    labelCol=LABEL_COL,
    numTrees=100,
    maxDepth=8,
    seed=42
)

rf_selector_model = rf_selector.fit(train_sample_vec)

print("Random Forest trained successfully for feature importance.")

"""#4.1 Ranked based on Feature Importance"""

rf_importances = rf_selector_model.featureImportances.toArray()

importance_df = pd.DataFrame({
    "feature": feature_cols,
    "importance": rf_importances
})

importance_df = importance_df.sort_values(
    by="importance",
    ascending=False
).reset_index(drop=True)

print("Top 30 features based on Random Forest importance:")
display(importance_df.head(30))

top_n = 30
plot_df = importance_df.head(top_n).copy()

plt.figure(figsize=(10, 7))
plt.barh(plot_df["feature"][::-1], plot_df["importance"][::-1])
plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 30 Random Forest Feature Importances")
plt.tight_layout()
plt.show()

"""#4.2 Selection of Top 20 Features"""

TOP_N_FEATURES = 20

selected_features = importance_df.head(TOP_N_FEATURES)["feature"].tolist()

print("Selected features:")
for f in selected_features:
    print(f)

print("\nNumber of selected features:", len(selected_features))

"""##5.Linear Regression"""

assembler = VectorAssembler(
    inputCols=selected_features,
    outputCol="features"
)

train_vec = assembler.transform(train_df).select("features", LABEL_COL)
test_vec = assembler.transform(test_df).select("features", LABEL_COL)

print("Feature vector created.")

scaler = StandardScaler(
    inputCol="features",
    outputCol="scaledFeatures",
    withStd=True,
    withMean=False
)

scaler_model = scaler.fit(train_vec)

train_scaled = scaler_model.transform(train_vec)
test_scaled = scaler_model.transform(test_vec)

print("Features scaled successfully.")

"""#5.1 Linear Regression tuning"""

lr = LinearRegression(
    featuresCol="scaledFeatures",
    labelCol=LABEL_COL
)

paramGrid_lr = (ParamGridBuilder()
    .addGrid(lr.regParam, [0.0, 0.001, 0.01, 0.05])
    .addGrid(lr.elasticNetParam, [0.0, 0.25, 0.5, 0.75, 1.0])
    .addGrid(lr.maxIter, [30, 50, 80])
    .build())

evaluator = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="rmse"
)

cv_lr = CrossValidator(
    estimator=lr,
    estimatorParamMaps=paramGrid_lr,
    evaluator=evaluator,
    numFolds=3,
    parallelism=2
)

lr_model = cv_lr.fit(train_scaled)

print("Linear Regression training completed.")

"""#5.2 Extract Best Parameter"""

best_lr_model = lr_model.bestModel

print("Best Parameters (LR Unweighted):")
print("regParam:", best_lr_model._java_obj.getRegParam())
print("elasticNetParam:", best_lr_model._java_obj.getElasticNetParam())
print("maxIter:", best_lr_model._java_obj.getMaxIter())

"""#5.3 Evaulate Model"""

pred_lr = best_lr_model.transform(test_scaled)

rmse = evaluator.evaluate(pred_lr)

mae_eval = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="mae"
)

r2_eval = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="r2"
)

mae = mae_eval.evaluate(pred_lr)
r2 = r2_eval.evaluate(pred_lr)

print("LR RMSE:", rmse)
print("LR MAE:", mae)
print("LR R2:", r2)

"""#5.4 Extract LR coefficients"""

coefficients = best_lr_model.coefficients.toArray()

coef_df = pd.DataFrame({
    "feature": selected_features,
    "coefficient": coefficients
})

coef_df["abs_coefficient"] = coef_df["coefficient"].abs()

coef_df = coef_df.sort_values(
    by="abs_coefficient",
    ascending=False
)

coef_df

plot_sample = pred_lr.select("prediction", LABEL_COL).sample(
    fraction=0.05,
    seed=42
)

plot_pd = plot_sample.toPandas()

plot_pd["residual"] = plot_pd[LABEL_COL] - plot_pd["prediction"]

print("Sample size for plotting:", len(plot_pd))

plt.figure(figsize=(7,7))

plt.scatter(
    plot_pd[LABEL_COL],
    plot_pd["prediction"],
    alpha=0.3
)

plt.xlabel("Actual Interest Rate")
plt.ylabel("Predicted Interest Rate")
plt.title("Actual vs Predicted Interest Rate (LR)")

# perfect prediction line
min_val = min(plot_pd[LABEL_COL].min(), plot_pd["prediction"].min())
max_val = max(plot_pd[LABEL_COL].max(), plot_pd["prediction"].max())

plt.plot([min_val, max_val], [min_val, max_val], color="red")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(plot_pd["residual"], bins=50, kde=True)

plt.xlabel("Residual (Actual - Predicted)")
plt.title("Residual Distribution (LR)")
plt.show()

plt.figure(figsize=(7,5))

plt.scatter(
    plot_pd["prediction"],
    plot_pd["residual"],
    alpha=0.3
)

plt.axhline(0, color="red")

plt.xlabel("Predicted Interest Rate")
plt.ylabel("Residual")
plt.title("Residual vs Predicted (LR)")

plt.show()

"""##6.LR Weighted

# 6.1 Create weight column
"""

train_weighted = train_df.withColumn("weight", col(LABEL_COL))
test_weighted = test_df.withColumn("weight", col(LABEL_COL))

print("Weight column created successfully.")
train_weighted.select(LABEL_COL, "weight").show(5)

train_weighted_vec = assembler.transform(train_weighted).select("features", LABEL_COL, "weight")
test_weighted_vec = assembler.transform(test_weighted).select("features", LABEL_COL, "weight")

print("Weighted feature vectors created successfully.")

scaler_weighted_model = scaler.fit(train_weighted_vec)

train_weighted_scaled = scaler_weighted_model.transform(train_weighted_vec)
test_weighted_scaled = scaler_weighted_model.transform(test_weighted_vec)

print("Weighted features scaled successfully.")

"""##6.2 Weighted Tuning"""

wlr = LinearRegression(
    featuresCol="scaledFeatures",
    labelCol=LABEL_COL,
    weightCol="weight"
)

paramGrid_wlr = (ParamGridBuilder()
    .addGrid(wlr.regParam, [0.0, 0.001, 0.01, 0.05])
    .addGrid(wlr.elasticNetParam, [0.0, 0.25, 0.5, 0.75, 1.0])
    .addGrid(wlr.maxIter, [30, 50, 80])
    .build())

cv_wlr = CrossValidator(
    estimator=wlr,
    estimatorParamMaps=paramGrid_wlr,
    evaluator=evaluator,
    numFolds=3,
    parallelism=2
)

wlr_model = cv_wlr.fit(train_weighted_scaled)

print("Weighted Linear Regression training completed.")

"""##6.3 Extract Best Parameter"""

best_wlr_model = wlr_model.bestModel

print("Best Parameters (LR Weighted):")
print("regParam:", best_wlr_model._java_obj.getRegParam())
print("elasticNetParam:", best_wlr_model._java_obj.getElasticNetParam())
print("maxIter:", best_wlr_model._java_obj.getMaxIter())

"""##6.4 Evaulate"""

pred_wlr = best_wlr_model.transform(test_weighted_scaled)

rmse_wlr = evaluator.evaluate(pred_wlr) mae_wlr = mae_eval.evaluate(pred_wlr) r2_wlr = r2_eval.evaluate(pred_wlr)

print("Weighted LR RMSE:", rmse_wlr) print("Weighted LR MAE:", mae_wlr) print("Weighted LR R2:", r2_wlr)

plot_sample_wlr = pred_wlr.select("prediction", LABEL_COL).sample(
    fraction=0.05,
    seed=42
)

plot_wlr_pd = plot_sample_wlr.toPandas()

plot_wlr_pd["residual"] = plot_wlr_pd[LABEL_COL] - plot_wlr_pd["prediction"]

print("Sample size for plotting:", len(plot_wlr_pd))

plt.figure(figsize=(7,7))

plt.scatter(
    plot_wlr_pd[LABEL_COL],
    plot_wlr_pd["prediction"],
    alpha=0.3
)

plt.xlabel("Actual Interest Rate")
plt.ylabel("Predicted Interest Rate")
plt.title("Actual vs Predicted Interest Rate (Weighted LR)")

min_val = min(plot_wlr_pd[LABEL_COL].min(), plot_wlr_pd["prediction"].min())
max_val = max(plot_wlr_pd[LABEL_COL].max(), plot_wlr_pd["prediction"].max())

plt.plot([min_val, max_val], [min_val, max_val], color="red")

plt.show()

plt.figure(figsize=(8,5))

sns.histplot(plot_wlr_pd["residual"], bins=50, kde=True)

plt.xlabel("Residual (Actual - Predicted)")
plt.title("Residual Distribution (Weighted LR)")

plt.show()

plt.figure(figsize=(7,5))

plt.scatter(
    plot_wlr_pd["prediction"],
    plot_wlr_pd["residual"],
    alpha=0.3
)

plt.axhline(0, color="red")

plt.xlabel("Predicted Interest Rate")
plt.ylabel("Residual")
plt.title("Residual vs Predicted (Weighted LR)")

plt.show()

"""##7. Gradient Boosting Tress"""

train_vec = assembler.transform(train_df).select("features", LABEL_COL)
test_vec = assembler.transform(test_df).select("features", LABEL_COL)

print("Feature vectors prepared for GBT.")

"""##7.1 Subset Selection"""

train_vec_gbt_tune = train_vec.sample(
    withReplacement=False,
    fraction=0.20,
    seed=42
)

print("Original training rows:", train_vec.count())
print("GBT tuning subset rows:", train_vec_gbt_tune.count())



"""## 7.2 Tuning"""

gbt = GBTRegressor(
    featuresCol="features",
    labelCol=LABEL_COL,
    seed=42
)

paramGrid_gbt = (ParamGridBuilder()
    .addGrid(gbt.maxDepth, [3, 5, 7])
    .addGrid(gbt.maxIter, [40, 80])
    .addGrid(gbt.stepSize, [0.05, 0.1])
    .addGrid(gbt.subsamplingRate, [0.8, 1.0])
    .build())

cv_gbt = CrossValidator(
    estimator=gbt,
    estimatorParamMaps=paramGrid_gbt,
    evaluator=evaluator,
    numFolds=3,
    parallelism=2
)

gbt_cv_model = cv_gbt.fit(train_vec_gbt_tune)

print("GBT cross-validated tuning completed.")

"""##7.3 Extract Best Features"""

best_gbt_tuned = gbt_cv_model.bestModel

best_maxDepth = best_gbt_tuned._java_obj.getMaxDepth()
best_maxIter = best_gbt_tuned._java_obj.getMaxIter()
best_stepSize = best_gbt_tuned._java_obj.getStepSize()
best_subsamplingRate = best_gbt_tuned._java_obj.getSubsamplingRate()

print("Best Parameters (GBT):")
print("maxDepth:", best_maxDepth)
print("maxIter:", best_maxIter)
print("stepSize:", best_stepSize)
print("subsamplingRate:", best_subsamplingRate)

"""##7.4 Implimentation"""

final_gbt = GBTRegressor(
    featuresCol="features",
    labelCol=LABEL_COL,
    maxDepth=best_maxDepth,
    maxIter=best_maxIter,
    stepSize=best_stepSize,
    subsamplingRate=best_subsamplingRate,
    seed=42
)

final_gbt_model = final_gbt.fit(train_vec)

print("Final GBT trained on full training data.")

evaluator = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="rmse"
)

mae_eval = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="mae"
)

r2_eval = RegressionEvaluator(
    labelCol=LABEL_COL,
    predictionCol="prediction",
    metricName="r2"
)

pred_gbt = final_gbt_model.transform(test_vec)

rmse_gbt = evaluator.evaluate(pred_gbt)
mae_gbt = mae_eval.evaluate(pred_gbt)
r2_gbt = r2_eval.evaluate(pred_gbt)

print("GBT RMSE:", rmse_gbt)
print("GBT MAE:", mae_gbt)
print("GBT R2:", r2_gbt)

"""##7.3 Feature Importance"""

importances = final_gbt_model.featureImportances.toArray()

importance_df = pd.DataFrame({
    "feature": selected_features,
    "importance": importances
})

importance_df = importance_df.sort_values(
    by="importance",
    ascending=False
)


plt.figure(figsize=(8,6))

plt.barh(
    importance_df["feature"][:10],
    importance_df["importance"][:10]
)

plt.gca().invert_yaxis()

plt.xlabel("Importance")
plt.ylabel("Feature")
plt.title("Top 10 Feature Importance (GBT)")

plt.show()

plot_df = pred_gbt.select(LABEL_COL, "prediction").sample(fraction=0.02, seed=42).toPandas()

plot_df.columns = ["actual", "predicted"]

plt.figure(figsize=(7,7))

plt.scatter(plot_df["actual"], plot_df["predicted"], alpha=0.4)

min_val = plot_df["actual"].min()
max_val = plot_df["actual"].max()

plt.plot([min_val, max_val], [min_val, max_val], color="red")

plt.xlabel("Actual Interest Rate")
plt.ylabel("Predicted Interest Rate")
plt.title("Actual vs Predicted Interest Rates (GBT)")

plt.show()

plot_df["residual"] = plot_df["actual"] - plot_df["predicted"]

plt.figure(figsize=(7,7))

plt.scatter(plot_df["predicted"], plot_df["residual"], alpha=0.4)

plt.axhline(0, color="red")

plt.xlabel("Predicted Interest Rate")
plt.ylabel("Residual")
plt.title("Residuals vs Predicted Values")

plt.show()

plt.figure(figsize=(7,6))

plt.hist(plot_df["residual"], bins=40)

plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.title("Residual Distribution")

plt.show()

